name: network_cool_client_example
description: "Example of Network Cool Client"
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  network_cool_client:
    path: ../

dev_dependencies:
  coolint: 2.0.1
  test: ^1.25.15
