name: network_cool_client
description: "A robust Dart package for efficient network request handling, session management, real-time network state tracking, and seamless error handling for modern applications."
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  http: any
  meta: any

dev_dependencies:
  coolint: 2.0.1
  test: ^1.25.15
