name: ncc
description: "A robust Dart package for efficient network request handling, session management, real-time network state tracking, and seamless error handling for modern applications."
version: 0.0.6

repository: https://github.com/coolosos/networkcoolclient
issue_tracker: https://github.com/coolosos/networkcoolclient/issues
homepage: https://github.com/coolosos
topics:
  - http
  - network
  - protocols
  - session

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  http: ">=1.5.0 <2.0.0"
  meta: ">=1.16.0 <2.0.0"

dev_dependencies:
  coolint: ^2.1.2
  test: ^1.26.3
