name: Validate
on:
  pull_request:
    branches: 
        - 'main'
    types: 
        - ready_for_review
        - synchronize
        - opened

jobs:
  spellcheck: 
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: streetsidesoftware/cspell-action@v7.1.2
  validate:
    name: Analyse
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: dart-lang/setup-dart@v1

      - run: dart pub get 

      - run: dart analyze --fatal-warnings
      - run: dart format lib --set-exit-if-changed  

      - run: dart test --coverage=coverage
      - run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib
      - run: dart run .github/check_coverage/check_coverage.dart 90.0